export const INITIAL_COMPANIES = [
  {
    id: 'comp_novatech',
    name: 'NovaTech Solutions',
    slug: 'novatech',
    officialEmail: 'contact@novatech.demo',
    website: 'https://novatech.demo',
    industry: 'Software & AI',
    country: 'United States',
    city: 'San Francisco',
    companySize: '50-200',
    description: 'Leading provider of AI-driven software solutions.',
    verificationStatus: 'APPROVED',
    createdAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'comp_brighthire',
    name: 'BrightHire Technologies',
    slug: 'brighthire',
    officialEmail: 'contact@brighthire.demo',
    website: 'https://brighthire.demo',
    industry: 'Technology Recruitment',
    country: 'United Kingdom',
    city: 'London',
    companySize: '10-50',
    description: 'Next-generation tech recruitment platform.',
    verificationStatus: 'APPROVED',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const INITIAL_USERS = [
  {
    id: 'user_platform_admin',
    companyId: null,
    name: 'Platform Admin',
    email: 'admin@workproof.demo',
    password: 'demo123',
    role: 'PLATFORM_ADMIN',
    status: 'ACTIVE',
    createdAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'user_admin_001',
    companyId: 'comp_novatech',
    name: 'Sarah Ahmed',
    email: 'admin@novatech.demo',
    password: 'demo123',
    role: 'COMPANY_ADMIN',
    status: 'ACTIVE',
    createdAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'user_emp_001',
    companyId: 'comp_novatech',
    name: 'Ayan Malik',
    email: 'ayan@demo.com',
    password: 'demo123',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user_rec_001',
    companyId: 'comp_brighthire',
    name: 'Hamza Khan',
    email: 'recruiter@brighthire.demo',
    password: 'demo123',
    role: 'RECRUITER',
    status: 'ACTIVE',
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const INITIAL_EMPLOYEES = [
  {
    id: 'emp_001',
    companyId: 'comp_novatech',
    userId: 'user_emp_001',
    name: 'Ayan Malik',
    email: 'ayan@demo.com',
    jobTitle: 'Software Engineer',
    department: 'Engineering',
    joiningDate: '2024-01-15',
    employmentStatus: 'active',
    profileVisibility: 'private',
    performance: 4.7,
    growthStatus: 'Promotion Ready',
    growthInsights: {
      strengths: ['Strong technical performance', 'Consistently delivers on time', 'Growing leadership ability'],
      development: ['Cloud Architecture', 'Mentorship skills'],
      promotionReadiness: 85,
      nextRole: 'Senior Software Engineer',
    }
  },
  {
    id: 'emp_002',
    companyId: 'comp_novatech',
    userId: 'user_emp_002',
    name: 'Sara Ali',
    email: 'sara@novatech.demo',
    jobTitle: 'Data Analyst',
    department: 'Analytics',
    joiningDate: '2024-03-10',
    employmentStatus: 'active',
    profileVisibility: 'private',
    performance: 4.4,
    growthStatus: 'Developing',
  },
  {
    id: 'emp_003',
    companyId: 'comp_novatech',
    userId: 'user_emp_003',
    name: 'Usman Raza',
    email: 'usman@novatech.demo',
    jobTitle: 'UI/UX Designer',
    department: 'Design',
    joiningDate: '2023-08-01',
    employmentStatus: 'active',
    profileVisibility: 'private',
    performance: 4.8,
    growthStatus: 'High Potential',
  },
  {
    id: 'emp_004',
    companyId: 'comp_novatech',
    userId: 'user_emp_004',
    name: 'Fatima Khan',
    email: 'fatima@novatech.demo',
    jobTitle: 'DevOps Engineer',
    department: 'Engineering',
    joiningDate: '2024-05-20',
    employmentStatus: 'active',
    profileVisibility: 'private',
    performance: 4.5,
    growthStatus: 'Developing',
  },
  {
    id: 'emp_005',
    companyId: 'comp_novatech',
    userId: 'user_emp_005',
    name: 'Omar Hassan',
    email: 'omar@novatech.demo',
    jobTitle: 'Product Manager',
    department: 'Product',
    joiningDate: '2023-11-15',
    employmentStatus: 'active',
    profileVisibility: 'private',
    performance: 4.6,
    growthStatus: 'High Potential',
  },
  {
    id: 'emp_006',
    companyId: 'comp_novatech',
    userId: 'user_emp_006',
    name: 'Zara Iqbal',
    email: 'zara@novatech.demo',
    jobTitle: 'Frontend Developer',
    department: 'Engineering',
    joiningDate: '2025-01-10',
    employmentStatus: 'active',
    profileVisibility: 'private',
    performance: 4.3,
    growthStatus: 'Developing',
  },
];

export const INITIAL_SKILLS = [
  { id: 'skill_001', companyId: 'comp_novatech', employeeId: 'emp_001', name: 'Python', level: 'Advanced', verified: true, verificationDate: '2026-01-15', endorsements: 5 },
  { id: 'skill_002', companyId: 'comp_novatech', employeeId: 'emp_001', name: 'Machine Learning', level: 'Intermediate', verified: true, verificationDate: '2026-01-15', endorsements: 3 },
  { id: 'skill_003', companyId: 'comp_novatech', employeeId: 'emp_001', name: 'SQL', level: 'Advanced', verified: true, verificationDate: '2025-12-01', endorsements: 4 },
  { id: 'skill_004', companyId: 'comp_novatech', employeeId: 'emp_001', name: 'React', level: 'Intermediate', verified: false, verificationDate: null, endorsements: 2 },
];

export const INITIAL_PROJECTS = [
  { id: 'proj_001', companyId: 'comp_novatech', employeeId: 'emp_001', name: 'AI Customer Support System', role: 'Backend Developer', technologies: ['Python', 'FastAPI', 'PostgreSQL'], status: 'completed', impact: 'Reduced support processing time by 35%', duration: '6 months', verified: true, verificationDate: '2025-12-15' },
  { id: 'proj_002', companyId: 'comp_novatech', employeeId: 'emp_001', name: 'Predictive Sales Analytics', role: 'ML Developer', technologies: ['Python', 'Scikit-learn', 'Pandas'], status: 'completed', impact: 'Improved sales predictions by 28%', duration: '4 months', verified: true, verificationDate: '2026-02-01' },
];

export const INITIAL_ACHIEVEMENTS = [
  { id: 'ach_001', companyId: 'comp_novatech', employeeId: 'emp_001', title: 'Completed AI project ahead of schedule' },
  { id: 'ach_002', companyId: 'comp_novatech', employeeId: 'emp_001', title: 'Mentored 2 junior developers' },
  { id: 'ach_003', companyId: 'comp_novatech', employeeId: 'emp_001', title: 'Exceeded quarterly targets 3 quarters' },
  { id: 'ach_004', companyId: 'comp_novatech', employeeId: 'emp_001', title: 'Recognized as high-potential employee' },
];

export const INITIAL_PERFORMANCE_RECORDS = [
  { id: 'perf_001', companyId: 'comp_novatech', employeeId: 'emp_001', month: 'Jan', year: 2026, overallScore: 4.5, projectDelivery: 4.6, technicalGrowth: 4.4, collaboration: 4.5, communication: 4.4, leadership: 4.1 },
  { id: 'perf_002', companyId: 'comp_novatech', employeeId: 'emp_001', month: 'Feb', year: 2026, overallScore: 4.6, projectDelivery: 4.7, technicalGrowth: 4.5, collaboration: 4.6, communication: 4.5, leadership: 4.2 },
  { id: 'perf_003', companyId: 'comp_novatech', employeeId: 'emp_001', month: 'Mar', year: 2026, overallScore: 4.7, projectDelivery: 4.8, technicalGrowth: 4.6, collaboration: 4.7, communication: 4.6, leadership: 4.3 },
  { id: 'perf_004', companyId: 'comp_novatech', employeeId: 'emp_001', month: 'Apr', year: 2026, overallScore: 4.8, projectDelivery: 4.9, technicalGrowth: 4.7, collaboration: 4.8, communication: 4.7, leadership: 4.4 },
];

export const INITIAL_FEEDBACK = [
  { id: 'fb_001', companyId: 'comp_novatech', employeeId: 'emp_001', type: 'manager', from: 'Sarah Ahmed', date: '2026-01-15', rating: 4.8, text: 'Ayan demonstrated exceptional leadership on the AI project. Consistently delivers high-quality code and mentors junior developers effectively.' },
  { id: 'fb_002', companyId: 'comp_novatech', employeeId: 'emp_001', type: 'peer', from: 'Sara Ali', date: '2025-12-20', rating: 4.5, text: 'Great team player. Always willing to help others and share knowledge.' },
];

export const INITIAL_ACTIVITIES = [
  {
    id: 'act_001',
    companyId: 'comp_novatech',
    actor: 'Ayan Malik',
    actorRole: 'EMPLOYEE',
    action: 'COMPLETED_PROJECT',
    target: 'Customer Portal Redesign',
    timestamp: '2026-07-26T10:30:00',
    status: 'SUCCESS',
    metadata: { type: 'milestone' },
  },
  {
    id: 'act_002',
    companyId: 'comp_novatech',
    actor: 'Sara Ali',
    actorRole: 'EMPLOYEE',
    action: 'EARNED_SKILL',
    target: 'Advanced SQL',
    timestamp: '2026-07-26T09:15:00',
    status: 'SUCCESS',
    metadata: { type: 'skill' },
  },
];