import { DataConnect } from 'firebase-admin/data-connect';

export interface ConnectorConfig {
  connector: string;
  service: string;
  location: string;
}
export declare const connectorConfig: ConnectorConfig;

export interface ExecuteGraphqlResponse<T> {
  data: T;
}

export declare function getUserByEmail(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getUserById(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getCompanyById(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getCompanyByName(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getCompanyByEmail(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getEmployeeById(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getEmployeeByEmail(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listEmployeesByCompany(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function searchEmployees(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getSkillByName(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listSkillsByEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getEmployeeSkillByPair(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listProjectsByEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listProjectsByCompany(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listBehaviorRatings(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function latestBehaviorRatings(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listAchievements(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listPerformanceReviews(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getLatestPerformanceReview(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listMonthlyReports(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getMonthlyReportByKey(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getPrivacyByEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getEmployeeEmploymentStatus(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getPublicProfileByEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getPublicProfileBySlug(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function checkSlugExists(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listPublicProfiles(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getVerificationCorrectionById(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listVerificationCorrectionsByEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listVerificationCorrectionsByCompany(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getJobOpportunityById(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listJobOpportunitiesByRecruiter(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listJobOpportunitiesByEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function countJobOpportunitiesByStatus(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listEmploymentLinksByPerson(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getEmploymentLinkByEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getCurrentEmploymentLink(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listNotificationsByUser(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listUnreadNotificationsByUser(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getNotificationById(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function countUnreadNotifications(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listAuditLogs(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function countAuditLogs(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listInternalProjectsByCompany(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getInternalProjectById(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getInvitationByToken(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function checkPendingInvitation(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function getSavedCandidate(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function listSavedCandidatesByRecruiter(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function companyEmployeeStats(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function companySkillDistribution(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function adminDashboardStats(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function findPlatformAdmins(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function adminListCompanies(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function allOpportunityStatuses(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function topSkills(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createUser(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateUserLastLogin(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function setUserCompanyAndEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createCompany(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function setCompanyAdmin(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateCompanyStatus(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createCompanyMembership(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function softDeleteEmployee(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function verifyEmployeeRecord(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function endEmployeeEmployment(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createSkill(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function addEmployeeSkill(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateEmployeeSkill(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createProject(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateProject(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createBehaviorRating(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createAchievement(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function verifyAchievement(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createPerformanceReview(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createMonthlyReport(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateMonthlyReport(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createPrivacySettings(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updatePrivacySettings(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function transferPrivacyOwnership(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function markPrivacyPublished(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createPublicProfile(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updatePublicProfileVisibility(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function incrementPublicProfileViews(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createVerificationCorrection(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateVerificationCorrectionStatus(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createJobOpportunity(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateJobOpportunityStatus(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createEmploymentLink(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function markEmploymentLinkLeft(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function attachUserToEmploymentLinks(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createNotification(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function markNotificationRead(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function markAllNotificationsRead(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createAuditLog(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createInternalProject(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateInternalProject(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function softDeleteInternalProject(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function createInvitation(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function markInvitationAccepted(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function saveCandidate(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function updateSavedCandidateNotes(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;
export declare function deleteSavedCandidate(dcOrVars?: DataConnect | Record<string, any>, vars?: Record<string, any>): Promise<ExecuteGraphqlResponse<any>>;